[2025-10-30T06:07:41.595+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2025-10-30T06:07:38.848256+00:00 [queued]>
[2025-10-30T06:07:41.599+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2025-10-30T06:07:38.848256+00:00 [queued]>
[2025-10-30T06:07:41.599+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-10-30T06:07:41.610+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2025-10-30 06:07:38.848256+00:00
[2025-10-30T06:07:41.613+0000] {standard_task_runner.py:57} INFO - Started process 25720 to run task
[2025-10-30T06:07:41.616+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2025-10-30T06:07:38.848256+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpc5gv2nkp']
[2025-10-30T06:07:41.616+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask extract_task
[2025-10-30T06:07:41.645+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2025-10-30T06:07:38.848256+00:00 [running]> on host codespaces-497b64
[2025-10-30T06:07:41.689+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T06:07:38.848256+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T06:07:38.848256+00:00'
[2025-10-30T06:07:41.690+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T06:07:41.690+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-extract-data.csv']
[2025-10-30T06:07:41.698+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T06:07:41.702+0000] {subprocess.py:93} INFO - --2025-10-30 06:07:41--  https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv
[2025-10-30T06:07:41.716+0000] {subprocess.py:93} INFO - Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
[2025-10-30T06:07:41.717+0000] {subprocess.py:93} INFO - Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
[2025-10-30T06:07:41.982+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2025-10-30T06:07:41.983+0000] {subprocess.py:93} INFO - 2025-10-30 06:07:41 ERROR 404: Not Found.
[2025-10-30T06:07:41.983+0000] {subprocess.py:93} INFO - 
[2025-10-30T06:07:41.984+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2025-10-30T06:07:41.989+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2025-10-30T06:07:41.992+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=challenge_dag, task_id=extract_task, execution_date=20251030T060738, start_date=20251030T060741, end_date=20251030T060741
[2025-10-30T06:07:42.002+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 25720)
[2025-10-30T06:07:42.029+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-10-30T06:07:42.043+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
